# Generated by Django 5.1.6 on 2025-02-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.AlterModelOptions(
            name="assettransfers",
            options={},
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="maintenancereminders",
            options={},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name_plural": "Users"},
        ),
    ]
