# Generated by Django 5.1.6 on 2025-03-04 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="needs_sterilization",
        ),
        migrations.AddField(
            model_name="assettransfer",
            name="transferred_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="home_lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_equipment",
                to="api.lab",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="equipment",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="project",
            name="lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.lab",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="current_lab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_equipment",
                to="api.lab",
            ),
        ),
    ]
