# Generated by Django 5.1.6 on 2025-02-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_assettransfers_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
