# Generated by Django 5.1.6 on 2025-02-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_users_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
