# Generated by Django 5.1.6 on 2025-02-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_project_assettransfers_is_synced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="email_hash",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
