# Generated by Django 5.1.6 on 2025-02-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_users_email_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="email_hash",
        ),
    ]
