# Generated by Django 5.1.6 on 2025-02-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_users_email_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_staff",
        ),
    ]
