# Generated by Django 5.1.6 on 2025-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_users_is_active_remove_users_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
