# Generated by Django 5.1.6 on 2025-02-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_users_is_active_users_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("student", "Student"),
                    ("lab manager", "Lab Manager"),
                    ("Technician", "Technician"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
