directories:
  output: dist_electron
  buildResources: build
appId: com.iveims.app
productName: IVEIMS
files:
  - filter:
      - main.js
      - frontend/ims/dist/**/*
win:
  target: nsis
electronVersion: 35.0.0
